### ISSUE TITLE
Logs not updating sometimes/always?

### ISSUE THREAD

**Issue by skx** [skx/dhcp.io#13]
A [twitter user](https://twitter.com/bulkanevcimen) [reports](https://twitter.com/bulkanevcimen/status/684903103884201985) that logs aren't showing updates some/all of the time.

Secondly they say that they "can't connect".  There are no details on that, so I assume that means the dynamic hostname they've set isn't reachable - that would be outside the scope of this issue and code.

**Comment by bulkan** [comment]
Hi @skx 

Even when I run the CURL command manually the logs aren't updated even though the POST request is successful

`curl -X POST https://dhcp.io/set --data 'token=<token>'`

**Comment by skx** [comment]
Thanks for the reminder.  I looked into this and still can't understand how this can happen.

When a request is made the code:

* Reads the request in [DHCP::Application::set()](https://github.com/skx/dhcp.io/blob/master/lib/DHCP/Application.pm#L745).
* That makes some basic checks then calls `setRecord`.
* The [setRecord](https://github.com/skx/dhcp.io/blob/master/lib/DHCP/User.pm#L352) is very simple:
** If the old record and new are the same [it returns, doing nothing](https://github.com/skx/dhcp.io/blob/master/lib/DHCP/User.pm#L385).
** If there is an existing/old record defined [it is removed](https://github.com/skx/dhcp.io/blob/master/lib/DHCP/User.pm#L395).
** After that [the new record is set](https://github.com/skx/dhcp.io/blob/master/lib/DHCP/User.pm#L404).
** Finally [the log-entry is added](https://github.com/skx/dhcp.io/blob/master/lib/DHCP/User.pm#L404).

So barring the case where old-ip == new-ip I'm struggling to see how this could fail.  Yes the SQL update could fail but in that case we'd see a `die` rather than a successful result.

**Comment by skx** [comment]
If you could share your login, and the names of any zones you're updating I'll look further.

**Comment by skx** [comment]
D'oh.  I'm an idiot.  This should be sorted now.

NOTE:  Logs page shows "oldest -> newest", with most recent changes at the bottom.

**Comment by bulkan** [comment]
Thanks the logs are updating now

**Comment by skx** [comment]
Thanks for the confirmation.

In conclusion: Logs were always being stored, but the "view logs" code was broken.
